FROM node:22-bullseye

COPY ./ /app

# some environment defaults
ENV NODE_ENV development
ENV PORT 8080
ENV LOG_LEVEL debug
ENV DEBUG debug
ENV APPLICATION_NAME=sna-camp-admin-pages

WORKDIR /app

RUN npm install

EXPOSE 8080
EXPOSE 9229

ENTRYPOINT ["node_modules/.bin/nodemon"]
CMD ["--watch", "--ignore node_modules", "--inspect=0.0.0.0:9229", "bin/www"]
