networks:
  internal:
    internal: true

volumes:
  postgres-data:
    driver: local

services:

  caddy:
    image: docker pull ghcr.io/iarekylew00t/caddy-cloudflare:latest
    container_name: caddy_snacamp_form
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/caddyData:/data
      - ./caddy/caddyConfig:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    links:
      - client
      - postgrest
    environment:
      CF_ZONE_JUJHAR_COM_TOKEN: "${CF_ZONE_JUJHAR_COM_TOKEN}"
      CF_API_TOKEN: "${CF_API_TOKEN}"
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.jujhar.project: "sna-camp-reg-form"
    networks:
      - default
      - internal


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "80/tcp"
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.jujhar.project: "sna-camp-reg-form"
    networks:
      - internal

  ################
  # postgres-db #
  ################
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes:
      # anything in initdb directory is created in the database
      # see "How to extend this image" section at https://hub.docker.com/r/_/postgres/
      - "./initdb:/docker-entrypoint-initdb.d"
      # PGDATA directory is persisted between restarts
      - "postgres-data:/var/lib/postgresql/data:Z"
    networks:
      - default
      - internal
    restart: unless-stopped
    labels:
      com.jujhar.mainDatabase: "true"

  #############
  # postgrest #
  #############
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:latest
    # ports:
    #   - "3000:3000"
    # Available environment variables documented here:
    # https://postgrest.org/en/latest/configuration.html#environment-variables
    environment:
      # The standard connection URI format, documented at
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      # The name of which database schema to expose to REST clients
      - PGRST_DB_SCHEMA=${DB_SCHEMA}
      # The database role to use when no client authentication is provided
      - PGRST_DB_ANON_ROLE=${DB_ANON_ROLE}
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      - PGRST_OPENAPI_SERVER_PROXY_URI=https://postgres.home.lan
    restart: unless-stopped
    links:
      - postgres
    networks:
      - internal

  ##############
  # swagger-ui #
  ##############
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:latest
    ports:
      - "192.168.10.13:8080:8080"
    environment:
      - API_URL=https://postgres.home.lan/
    restart: unless-stopped
    networks:
      - default
