services:
  admin-page:
    build:
      context: ./admin-page
      dockerfile: Dockerfile.dev
    ports:
      - "3040:8080"
      - "9229:9229"
    expose:
      - "8080/tcp"
      - "9229/tcp"
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.jujhar.project: "sna-camp-reg-admin-page"
