networks:
  internal:
    internal: true

volumes:
  postgres-data:
    driver: local

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "80/tcp"
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.jujhar.project: "sna-camp-reg-form"
    networks:
      - internal
