// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");
const { faker } = require("@faker-js/faker");
faker.setLocale("en_GB");
const { describe } = require("mocha");

describe(">16 flow", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it(">16 years old flow", async function () {
    await driver.get("http://localhost:3000/");
    await driver.findElement(By.id("firstname")).sendKeys(faker.name.firstName());
    await driver.findElement(By.id("surname")).sendKeys(faker.name.lastName());
    await driver.findElement(By.id("email")).sendKeys(faker.internet.email());
    await driver
      .findElement(By.name("gender"))
      .sendKeys(Math.floor(Math.random() * 10) > 5 ? "Male" : "Female");
    await driver
      .findElement(By.id("age"))
      .sendKeys(faker.mersenne.rand(16, 85));
    await driver
      .findElement(By.id("mobile"))
      .sendKeys(faker.phone.number("07### ### ###"));
    await driver
      .findElement(By.id("address1"))
      .sendKeys(faker.address.streetAddress(true));
    await driver.findElement(By.id("city")).sendKeys(faker.address.cityName());
    await driver
      .findElement(By.id("postcode"))
      .sendKeys(faker.address.zipCode());
    await driver
      .findElement(By.id("emergency-name"))
      .sendKeys(faker.name.fullName());
    await driver
      .findElement(By.id("emergency-number"))
      .sendKeys(faker.phone.number("07### ### ###"));
    await driver
      .findElement(By.name("t-shirt-size"))
      .sendKeys(Math.floor(Math.random() * 10) > 4 ? "Large" : "Small");
    await driver
      .findElement(By.name("avg-speed"))
      .sendKeys(
        Math.floor(Math.random() * 10) > 4 ? "Professional" : "Amateur"
      );
    await driver
      .findElement(By.id("medical-conditions"))
      .sendKeys(faker.random.words(8));
    await driver
      .findElement(By.id("hear-about-us"))
      .sendKeys(faker.random.words(12));

    // stripe iframe bits
    await driver.switchTo().frame(driver.findElement(By.xpath("//iframe")));
    await driver
      .findElement(By.name("cardnumber"))
      .sendKeys("4242 4242 4242 4242");
    await driver.findElement(By.name("exp-date")).sendKeys("04 / 24");
    await driver.findElement(By.name("cvc")).sendKeys(`242 ${Key.TAB}`);

    // switching back to main document
    await driver.switchTo().defaultContent();
    await driver.sleep(500);
    await driver.switchTo().defaultContent();
    await driver.findElement(By.id("card-button")).click();

    // check for success
    await driver.sleep(6500);
    const successMsgEl = await driver
      .findElement(By.id("final_message"))
      .getText();
    assert.match(successMsgEl, /^Everything processed successfully\./);
  });
});
