apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sna-camp-form

labels:
- includeSelectors: true
  pairs:
    projectName: sna-camp-form

resources:
  - namespace.yaml
  - frontend.yaml
  - ingress.yaml
  - sa.yaml
