apiVersion: kustomize.config.k8s.io/v1beta1
labels:
  - includeSelectors: true
    pairs:
      environment: production
resources:
  - ../base
images:
  - name: sna-camp-form-frontend
    newName: ghcr.io/jujhars13/sna-camp-form
    newTag: null
